
-- Lock down app_users and user_settings: this app uses a custom auth system; all
-- access goes through the manage-users edge function with the service role key
-- (which bypasses RLS). Add explicit deny policies so anon/authenticated clients
-- cannot read or write anything directly, even if a policy is later added by mistake.

-- app_users: block all direct client access
CREATE POLICY "Deny all client access to app_users"
  ON public.app_users
  AS RESTRICTIVE
  FOR ALL
  TO anon, authenticated
  USING (false)
  WITH CHECK (false);

-- user_settings: block all direct client access
CREATE POLICY "Deny all client access to user_settings"
  ON public.user_settings
  AS RESTRICTIVE
  FOR ALL
  TO anon, authenticated
  USING (false)
  WITH CHECK (false);

-- Tighten storage policies on montage-files. The bucket is private and files are
-- only ever served via signed URLs generated by edge functions (service role).
-- Remove the broad authenticated SELECT/DELETE/INSERT policies that allowed any
-- authenticated user to read or delete any other user's files.
DROP POLICY IF EXISTS "Authenticated users can view montage files" ON storage.objects;
DROP POLICY IF EXISTS "Authenticated users can delete own montage files" ON storage.objects;
DROP POLICY IF EXISTS "Authenticated users can upload montage files" ON storage.objects;
